# Generated by Django 4.0.5 on 2023-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.CharField(max_length=200),
        ),
    ]
