# Generated by Django 4.0.5 on 2023-04-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('posts', '0002_alter_like_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='actor',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'object')},
        ),
    ]
