# Generated by Django 4.0.5 on 2023-03-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_follow'),
        ('posts', '0003_alter_post_categories_alter_post_unlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='posts.post')),
                ('requests', models.ManyToManyField(blank=True, related_name='requests', to='app.author')),
            ],
        ),
    ]
