# Generated by Django 4.0.5 on 2023-03-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='posts.comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='posts.like')),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='posts.post')),
                ('requests', models.ManyToManyField(blank=True, related_name='requests', to='app.follow')),
            ],
        ),
    ]
