# Generated by Django 4.0.5 on 2023-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_follow_summary'),
        ('inbox', '0002_inbox_comments_inbox_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='app.follow'),
        ),
    ]
