# Generated by Django 4.0.5 on 2023-02-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
    ]
